# Test against this version of Node.js
environment:
  nodejs_version: "6"
  NSIS_ROOT: C:\nsis

init:
  - "SET PATH=%NSIS_ROOT%;%PATH%"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - cinst nsis -y -installArgs /D=%NSIS_ROOT%
  - ps: Install-Product node $env:nodejs_version x64
  # install modules
  - npm install
  - npm run release

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  # - npm test

artifacts:
  - path: releases/*.exe
    name: MyApp

# Don't actually build.
build: off